### ISSUE TITLE
Add GH attestations

### ISSUE THREAD

**Issue by tazarov** [amikos-tech/chroma-images#72]
https://github.com/actions/attest-build-provenance?tab=readme-ov-file#container-image

```yaml
- name: Attest
        uses: actions/attest-build-provenance@v2
        id: attest
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.build-and-push.outputs.digest }}
          push-to-registry: true
```

> [!IMPORTANT]
> What should be the subject hame here? We have multiple tags `for tag in $(echo '${{ steps.meta.outputs.tags }}' | grep '^ghcr.io'); do`
